//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossfitOpenStats.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competitor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competitor()
        {
            this.WorkoutScores = new HashSet<WorkoutScore>();
        }
    
        public int CompetitorId { get; set; }
        public string CompetitorName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Status { get; set; }
        public string PostCompStatus { get; set; }
        public string Gender { get; set; }
        public string ProfilePicS3Key { get; set; }
        public string CountryShortCode { get; set; }
        public string RegionalCode { get; set; }
        public string RegionId { get; set; }
        public string RegionName { get; set; }
        public string DivisionId { get; set; }
        public string Profession { get; set; }
        public string AffiliateId { get; set; }
        public string AffiliateName { get; set; }
        public Nullable<decimal> Age { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string TeamCaptain { get; set; }
        public Nullable<int> OverallRank { get; set; }
        public Nullable<int> OverallScore { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkoutScore> WorkoutScores { get; set; }
    }
}
