//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossfitOpenStats.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        public string PolicyNumber { get; set; }
        public System.DateTime PolicyEffectiveDate { get; set; }
        public System.DateTime PolicyExpirationDate { get; set; }
        public string PrimaryInsuredName { get; set; }
        public string PrimaryInsuredMailingAddress { get; set; }
        public string PrimaryInsuredCity { get; set; }
        public int PrimaryInsuredStateId { get; set; }
        public string PrimaryInsuredZipCode { get; set; }
        public int RiskConstructionId { get; set; }
        public int RiskYearBuilt { get; set; }
        public string RiskAddress { get; set; }
        public string RiskCity { get; set; }
        public int RiskStateId { get; set; }
        public string RiskZipCode { get; set; }
        public int PolicyId { get; set; }
    
        public virtual State PrimaryInsuredState { get; set; }
        public virtual RiskConstruction RiskConstruction { get; set; }
        public virtual State RiskState { get; set; }
    }
}
