//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossfitOpenStats.DbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PolicyDBEntities : DbContext
    {
        public PolicyDBEntities()
            : base("name=PolicyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Policy> Policies { get; set; }
        public virtual DbSet<RiskConstruction> RiskConstructions { get; set; }
        public virtual DbSet<State> States { get; set; }
    }
}
