//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossfitOpenStats.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkoutScore
    {
        public int Id { get; set; }
        public int CompetitorId { get; set; }
        public int Rank { get; set; }
        public string Score { get; set; }
        public string ScoreDisplay { get; set; }
        public string ScoreIdentifier { get; set; }
        public string Video { get; set; }
        public string Breakdown { get; set; }
    
        public virtual Competitor Competitor { get; set; }
    }
}
